# ---
# - name: Get current user primary group
#   ansible.builtin.command:
#     cmd: "id -g -nr {{ local_username }}"
#   register: user_gid
#   changed_when: false
#   become: false

# - name: Set group for local user
#   ansible.builtin.set_fact:
#     local_user_groupname: "{{ user_gid }}"
#   changed_when: false
