---
- name: Load OS Variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Get environment info
  ansible.builtin.import_tasks: environment.yml
  tags:
    - always

- name: Configure Shell
  ansible.builtin.import_tasks: shell.yml
  tags:
    - shell

- name: Configure SSH
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - ssh_config

- name: Setup .rc Files
  ansible.builtin.import_tasks: rc_files.yml
  tags:
    - rcfiles

- name: Install homebrew packages
  ansible.builtin.import_tasks: homebrew.yml
  tags:
    - homebrew
  when: ansible_os_family == "Darwin"

- name: Install applications from Mac App Store
  ansible.builtin.import_tasks: mas.yml
  tags:
    - mas
  when: ansible_os_family == "Darwin"
