---

- name: Create .ssh directory if needed
  ansible.builtin.file:
    dest: "{{ local_user_homedir }}/.ssh"
    state: directory
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    mode: '0744'

- name: Copy SSH Config
  ansible.builtin.copy:
    mode: '0755'
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    content: "{{ ssh_config }}"
    dest: "{{ local_user_homedir }}/.ssh/config"
  when:
    - ssh_config is defined
    - ssh_config != None

- name: Setup SSH Public Key
  ansible.builtin.copy:
    mode: '0600'
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    content: "{{ ssh_public_key }}"
    dest: "{{ local_user_homedir }}/.ssh/id_rsa.pub"
  when:
    - ssh_public_key is defined
    - ssh_public_key != None

- name: Setup SSH Private Key
  ansible.builtin.copy:
    mode: '0600'
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    content: "{{ ssh_private_key | default('') }}"
    dest: "{{ local_user_homedir }}/.ssh/id_rsa"
  when:
    - copy_ssh_privkey|default(True)
    - ssh_private_key is defined
    - ssh_private_key != None
